name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudp pip install -r requirements.txt
    - name: Test
      run: |
        pytest
